# You can view our full documentation here: https://docs.readme.com/docs/rdme
name: ReadMe GitHub Action 🦉

on:
  push:
    tags:
      - sit-*

jobs:
  push-to-readmeio:
    runs-on: ubuntu-latest
    steps:
      - name: Build docs
        run: ./.rdme-deploy/build.sh

      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: Deploy Docs to sit
        uses: readmeio/rdme@v8
        with:
          rdme: docs "./dist/docs/" --key=${{ secrets.README_API_KEY }} --version=1.0-sit
